<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Testing exceptions | Piotr Wittchen</title><meta name=keywords content="java,testing"><meta name=description content="In Java, we can test exceptions via unit tests in a few different ways. In this article, I&rsquo;ll present common methods of doing that. Nevertheless, I suppose we there are different methods as well.
First method is basically wrapping a method call with try-catch block, assigning an exception to a variable and performing appropriate assertion. In these examples, I&rsquo;m using JUnit for unit tests and Truth for assertions.
@Test public void shouldTestExceptionWithTryCatch() { Exception caughtException = null; try { throw new RuntimeExcetpion(&#34;message&#34;); } catch (final Exception e) { caughtException = e; } assertThat(caughtException)."><meta name=author content="Piotr Wittchen"><link rel=canonical href=https://wittchen.io/posts/testing-exceptions/><link crossorigin=anonymous href=/assets/css/stylesheet.cdcf872f971c70fddc7fd480e8457cd308ed0cf287b498bcdc6183fc6d147858.css integrity="sha256-zc+HL5cccP3cf9SA6EV80wjtDPKHtJi83GGD/G0UeFg=" rel="preload stylesheet" as=style><script defer crossorigin=anonymous src=/assets/js/highlight.f413e19d0714851f6474e7ee9632408e58ac146fbdbe62747134bea2fa3415e0.js integrity="sha256-9BPhnQcUhR9kdOfuljJAjlisFG+9vmJ0cTS+ovo0FeA=" onload=hljs.initHighlightingOnLoad()></script>
<link rel=icon href=https://wittchen.io/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://wittchen.io/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=https://wittchen.io/favicon-32x32.png><link rel=apple-touch-icon href=https://wittchen.io/apple-touch-icon.png><link rel=mask-icon href=https://wittchen.io/safari-pinned-tab.svg><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--hljs-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><meta property="og:title" content="Testing exceptions"><meta property="og:description" content="In Java, we can test exceptions via unit tests in a few different ways. In this article, I&rsquo;ll present common methods of doing that. Nevertheless, I suppose we there are different methods as well.
First method is basically wrapping a method call with try-catch block, assigning an exception to a variable and performing appropriate assertion. In these examples, I&rsquo;m using JUnit for unit tests and Truth for assertions.
@Test public void shouldTestExceptionWithTryCatch() { Exception caughtException = null; try { throw new RuntimeExcetpion(&#34;message&#34;); } catch (final Exception e) { caughtException = e; } assertThat(caughtException)."><meta property="og:type" content="article"><meta property="og:url" content="https://wittchen.io/posts/testing-exceptions/"><meta property="article:section" content="posts"><meta property="article:published_time" content="2018-09-04T19:49:26+00:00"><meta property="article:modified_time" content="2018-09-04T19:49:26+00:00"><meta property="og:site_name" content="Piotr Wittchen"><meta name=twitter:card content="summary"><meta name=twitter:title content="Testing exceptions"><meta name=twitter:description content="In Java, we can test exceptions via unit tests in a few different ways. In this article, I&rsquo;ll present common methods of doing that. Nevertheless, I suppose we there are different methods as well.
First method is basically wrapping a method call with try-catch block, assigning an exception to a variable and performing appropriate assertion. In these examples, I&rsquo;m using JUnit for unit tests and Truth for assertions.
@Test public void shouldTestExceptionWithTryCatch() { Exception caughtException = null; try { throw new RuntimeExcetpion(&#34;message&#34;); } catch (final Exception e) { caughtException = e; } assertThat(caughtException)."><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Posts","item":"https://wittchen.io/posts/"},{"@type":"ListItem","position":2,"name":"Testing exceptions","item":"https://wittchen.io/posts/testing-exceptions/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Testing exceptions","name":"Testing exceptions","description":"In Java, we can test exceptions via unit tests in a few different ways. In this article, I\u0026rsquo;ll present common methods of doing that. Nevertheless, I suppose we there are different methods as well.\nFirst method is basically wrapping a method call with try-catch block, assigning an exception to a variable and performing appropriate assertion. In these examples, I\u0026rsquo;m using JUnit for unit tests and Truth for assertions.\n@Test public void shouldTestExceptionWithTryCatch() { Exception caughtException = null; try { throw new RuntimeExcetpion(\u0026#34;message\u0026#34;); } catch (final Exception e) { caughtException = e; } assertThat(caughtException).","keywords":["java","testing"],"articleBody":"In Java, we can test exceptions via unit tests in a few different ways. In this article, I’ll present common methods of doing that. Nevertheless, I suppose we there are different methods as well.\nFirst method is basically wrapping a method call with try-catch block, assigning an exception to a variable and performing appropriate assertion. In these examples, I’m using JUnit for unit tests and Truth for assertions.\n@Test public void shouldTestExceptionWithTryCatch() { Exception caughtException = null; try { throw new RuntimeExcetpion(\"message\"); } catch (final Exception e) { caughtException = e; } assertThat(caughtException).hasMessageThat().isEqualTo(\"message\"); } In the second method, we can define a type of the thrown exception within the @Test annotation. It’s useful approach when we don’t want to test exception details like message and we care only about the type.\n@Test(expected = RuntimeException.class) public void shouldTestExceptionWithExpectedAnnotation() throws RuntimeException { throw new RuntimeException(\"message\"); } We can also test exceptions with AssertJ library as follows:\n@Test public void shouldTestExceptionWithAssertJ() throws RuntimeException { Throwable thrown = catchThrowable(this::throwException); org.assertj.core.api.Assertions .assertThat(thrown) .isInstanceOf(RuntimeException.class) .hasMessage(EXCEPTION_MESSAGE); } Another method allows us to test exception type, message and other details without wrapping method call with try-catch block, what increases code readibility and makes it clear. In order to achieve that, we need @Rule annotation and ExpectedException object like in the code snippet below. What is important in this example, we have to define assertions in the beginning and invoke method, which will throw an exception after these assertions. It’s different order than in a regular unit test.\n@Rule public ExpectedException expectedException = ExpectedException.none(); @Test public void shouldTestExceptionWithRuleAnnotation() throws RuntimeException { expectedException.expect(RuntimeException.class); expectedException.expectMessage(EXCEPTION_MESSAGE); throw new RuntimeException(\"message\"); } Alternatively, we can experiment with Vavr and Try interface.\n@Test public void shouldTestExceptionWithTryCatchAndVavr() { final Object object = Try .of(this::throwException) .toOption() .getOrElse(new ErrorObject()); assertThat(object).isInstanceOf(ErrorObject.class); } private Object throwException() { throw new RuntimeException(\"message\"); } private class ErrorObject {} We can even go crazy and prepare RxJava wrapper for our exception.\nprivate Completable toCompletable(final Runnable runnable) { return Completable.create(emitter - { try { runnable.run(); emitter.onComplete(); } catch (final Exception e) { emitter.onError(e); } }); } and write test like that:\n@Test public void shouldTestExceptionWithRxJava() { final Throwable throwable = toCompletable(this::throwException).blockingGet(); assertThat(throwable).isInstanceOf(RuntimeException.class); assertThat(throwable.getMessage()).isEqualTo(EXCEPTION_MESSAGE); } For sure, it shouldn’t be default choice and I wrote it just for a little experiment. Don’t treat that as a production-ready code (unless there’s a reson you really need something like that).\nI think, we can find even more ways of testing exceptions. In my opinion, solution with JUnit and @Rule annotation is the cleanest and most flexible one among all of the approaches presented here. It’s good to mention that last two approaches are just experiments. I also recommend Truth for writing assertions. Nevertheless, libraries like FEST, AssertJ and others, which have fluent interfaces helping in error analysis are also worth considering in daily usage.\nDo you know other (maybe better) approaches of testing exceptions in Java? Share them in comments :-).\n","wordCount":"483","inLanguage":"en","datePublished":"2018-09-04T19:49:26Z","dateModified":"2018-09-04T19:49:26Z","author":{"@type":"Person","name":"Piotr Wittchen"},"mainEntityOfPage":{"@type":"WebPage","@id":"https://wittchen.io/posts/testing-exceptions/"},"publisher":{"@type":"Organization","name":"Piotr Wittchen","logo":{"@type":"ImageObject","url":"https://wittchen.io/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://wittchen.io/ accesskey=h title="Piotr Wittchen (Alt + H)">Piotr Wittchen</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=https://wittchen.io/posts/ title=posts><span>posts</span></a></li><li><a href=https://wittchen.io/tags/ title=tags><span>tags</span></a></li><li><a href=https://wittchen.io/talks/ title=talks><span>talks</span></a></li><li><a href=https://wittchen.io/search/ title="search (Alt + /)" accesskey=/><span>search</span></a></li><li><a href=https://wittchen.io/contact/ title=contact><span>contact</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=https://wittchen.io/>Home</a>&nbsp;»&nbsp;<a href=https://wittchen.io/posts/>Posts</a></div><h1 class=post-title>Testing exceptions</h1><div class=post-meta><span title="2018-09-04 19:49:26 +0000 UTC">September 4, 2018</span>&nbsp;·&nbsp;3 min&nbsp;·&nbsp;483 words&nbsp;·&nbsp;Piotr Wittchen&nbsp;|&nbsp;<a href=https://github.com/pwittchen/wittchen.io/blob/master/content/posts/testing-exceptions.md rel="noopener noreferrer" target=_blank>Suggest Changes</a></div></header><div class=post-content><p>In Java, we can test exceptions via unit tests in a few different ways. In this article, I&rsquo;ll present common methods of doing that. Nevertheless, I suppose we there are different methods as well.</p><p>First method is basically wrapping a method call with try-catch block, assigning an exception to a variable and performing appropriate assertion. In these examples, I&rsquo;m using <a href=https://junit.org>JUnit</a> for unit tests and <a href=https://google.github.io/truth/>Truth</a> for assertions.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>shouldTestExceptionWithTryCatch</span><span class=o>()</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>  <span class=n>Exception</span> <span class=n>caughtException</span> <span class=o>=</span> <span class=kc>null</span><span class=o>;</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>  <span class=k>try</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>    <span class=k>throw</span> <span class=k>new</span> <span class=n>RuntimeExcetpion</span><span class=o>(</span><span class=s>&#34;message&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl>  <span class=o>}</span> <span class=k>catch</span> <span class=o>(</span><span class=kd>final</span> <span class=n>Exception</span> <span class=n>e</span><span class=o>)</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>    <span class=n>caughtException</span> <span class=o>=</span> <span class=n>e</span><span class=o>;</span>
</span></span><span class=line><span class=cl>  <span class=o>}</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>  <span class=n>assertThat</span><span class=o>(</span><span class=n>caughtException</span><span class=o>).</span><span class=na>hasMessageThat</span><span class=o>().</span><span class=na>isEqualTo</span><span class=o>(</span><span class=s>&#34;message&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>In the second method, we can define a type of the thrown exception within the <code>@Test</code> annotation. It&rsquo;s useful approach when we don&rsquo;t want to test exception details like message and we care only about the type.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span><span class=o>(</span><span class=n>expected</span> <span class=o>=</span> <span class=n>RuntimeException</span><span class=o>.</span><span class=na>class</span><span class=o>)</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>shouldTestExceptionWithExpectedAnnotation</span><span class=o>()</span> <span class=kd>throws</span> <span class=n>RuntimeException</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>  <span class=k>throw</span> <span class=k>new</span> <span class=n>RuntimeException</span><span class=o>(</span><span class=s>&#34;message&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>We can also test exceptions with AssertJ library as follows:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>shouldTestExceptionWithAssertJ</span><span class=o>()</span> <span class=kd>throws</span> <span class=n>RuntimeException</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>  <span class=n>Throwable</span> <span class=n>thrown</span> <span class=o>=</span> <span class=n>catchThrowable</span><span class=o>(</span><span class=k>this</span><span class=o>::</span><span class=n>throwException</span><span class=o>);</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>  <span class=n>org</span><span class=o>.</span><span class=na>assertj</span><span class=o>.</span><span class=na>core</span><span class=o>.</span><span class=na>api</span><span class=o>.</span><span class=na>Assertions</span>
</span></span><span class=line><span class=cl>      <span class=o>.</span><span class=na>assertThat</span><span class=o>(</span><span class=n>thrown</span><span class=o>)</span>
</span></span><span class=line><span class=cl>      <span class=o>.</span><span class=na>isInstanceOf</span><span class=o>(</span><span class=n>RuntimeException</span><span class=o>.</span><span class=na>class</span><span class=o>)</span>
</span></span><span class=line><span class=cl>      <span class=o>.</span><span class=na>hasMessage</span><span class=o>(</span><span class=n>EXCEPTION_MESSAGE</span><span class=o>);</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>Another method allows us to test exception type, message and other details without wrapping method call with try-catch block, what increases code readibility and makes it clear. In order to achieve that, we need <code>@Rule</code> annotation and <code>ExpectedException</code> object like in the code snippet below. What is important in this example, we have to define assertions in the beginning and invoke method, which will throw an exception after these assertions. It&rsquo;s different order than in a regular unit test.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=nd>@Rule</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=n>ExpectedException</span> <span class=n>expectedException</span> <span class=o>=</span> <span class=n>ExpectedException</span><span class=o>.</span><span class=na>none</span><span class=o>();</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>shouldTestExceptionWithRuleAnnotation</span><span class=o>()</span> <span class=kd>throws</span> <span class=n>RuntimeException</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>  <span class=n>expectedException</span><span class=o>.</span><span class=na>expect</span><span class=o>(</span><span class=n>RuntimeException</span><span class=o>.</span><span class=na>class</span><span class=o>);</span>
</span></span><span class=line><span class=cl>  <span class=n>expectedException</span><span class=o>.</span><span class=na>expectMessage</span><span class=o>(</span><span class=n>EXCEPTION_MESSAGE</span><span class=o>);</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>  <span class=k>throw</span> <span class=k>new</span> <span class=n>RuntimeException</span><span class=o>(</span><span class=s>&#34;message&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>Alternatively, we can experiment with <a href=https://www.vavr.io/>Vavr</a> and <code>Try</code> interface.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>shouldTestExceptionWithTryCatchAndVavr</span><span class=o>()</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>  <span class=kd>final</span> <span class=n>Object</span> <span class=n>object</span> <span class=o>=</span> 
</span></span><span class=line><span class=cl>    <span class=n>Try</span>
</span></span><span class=line><span class=cl>      <span class=o>.</span><span class=na>of</span><span class=o>(</span><span class=k>this</span><span class=o>::</span><span class=n>throwException</span><span class=o>)</span>
</span></span><span class=line><span class=cl>      <span class=o>.</span><span class=na>toOption</span><span class=o>()</span>
</span></span><span class=line><span class=cl>      <span class=o>.</span><span class=na>getOrElse</span><span class=o>(</span><span class=k>new</span> <span class=n>ErrorObject</span><span class=o>());</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>  <span class=n>assertThat</span><span class=o>(</span><span class=n>object</span><span class=o>).</span><span class=na>isInstanceOf</span><span class=o>(</span><span class=n>ErrorObject</span><span class=o>.</span><span class=na>class</span><span class=o>);</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=kd>private</span> <span class=n>Object</span> <span class=nf>throwException</span><span class=o>()</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>  <span class=k>throw</span> <span class=k>new</span> <span class=n>RuntimeException</span><span class=o>(</span><span class=s>&#34;message&#34;</span><span class=o>);</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=kd>private</span> <span class=kd>class</span> <span class=nc>ErrorObject</span> <span class=o>{}</span>
</span></span></code></pre></div><p>We can even go crazy and prepare RxJava wrapper for our exception.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=kd>private</span> <span class=n>Completable</span> <span class=nf>toCompletable</span><span class=o>(</span><span class=kd>final</span> <span class=n>Runnable</span> <span class=n>runnable</span><span class=o>)</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>  <span class=k>return</span> <span class=n>Completable</span><span class=o>.</span><span class=na>create</span><span class=o>(</span><span class=n>emitter</span> <span class=o>-&gt;</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>    <span class=k>try</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>      <span class=n>runnable</span><span class=o>.</span><span class=na>run</span><span class=o>();</span>
</span></span><span class=line><span class=cl>      <span class=n>emitter</span><span class=o>.</span><span class=na>onComplete</span><span class=o>();</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span> <span class=k>catch</span> <span class=o>(</span><span class=kd>final</span> <span class=n>Exception</span> <span class=n>e</span><span class=o>)</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>      <span class=n>emitter</span><span class=o>.</span><span class=na>onError</span><span class=o>(</span><span class=n>e</span><span class=o>);</span>
</span></span><span class=line><span class=cl>    <span class=o>}</span>
</span></span><span class=line><span class=cl>  <span class=o>});</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>and write test like that:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-java data-lang=java><span class=line><span class=cl><span class=nd>@Test</span>
</span></span><span class=line><span class=cl><span class=kd>public</span> <span class=kt>void</span> <span class=nf>shouldTestExceptionWithRxJava</span><span class=o>()</span> <span class=o>{</span>
</span></span><span class=line><span class=cl>  <span class=kd>final</span> <span class=n>Throwable</span> <span class=n>throwable</span> <span class=o>=</span> <span class=n>toCompletable</span><span class=o>(</span><span class=k>this</span><span class=o>::</span><span class=n>throwException</span><span class=o>).</span><span class=na>blockingGet</span><span class=o>();</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl>  <span class=n>assertThat</span><span class=o>(</span><span class=n>throwable</span><span class=o>).</span><span class=na>isInstanceOf</span><span class=o>(</span><span class=n>RuntimeException</span><span class=o>.</span><span class=na>class</span><span class=o>);</span>
</span></span><span class=line><span class=cl>  <span class=n>assertThat</span><span class=o>(</span><span class=n>throwable</span><span class=o>.</span><span class=na>getMessage</span><span class=o>()).</span><span class=na>isEqualTo</span><span class=o>(</span><span class=n>EXCEPTION_MESSAGE</span><span class=o>);</span>
</span></span><span class=line><span class=cl><span class=o>}</span>
</span></span></code></pre></div><p>For sure, it shouldn&rsquo;t be default choice and I wrote it just for a little experiment. Don&rsquo;t treat that as a production-ready code (unless there&rsquo;s a reson you really need something like that).</p><p>I think, we can find even more ways of testing exceptions. In my opinion, solution with JUnit and <code>@Rule</code> annotation is the cleanest and most flexible one among all of the approaches presented here. It&rsquo;s good to mention that last two approaches are just experiments. I also recommend Truth for writing assertions. Nevertheless, libraries like FEST, AssertJ and others, which have fluent interfaces helping in error analysis are also worth considering in daily usage.</p><p>Do you know other (maybe better) approaches of testing exceptions in Java? Share them in comments :-).</p></div><footer class=post-footer><ul class=post-tags><li><a href=https://wittchen.io/tags/java/>java</a></li><li><a href=https://wittchen.io/tags/testing/>testing</a></li></ul><nav class=paginav><a class=prev href=https://wittchen.io/posts/excluding-generated-code-from-jacoco-report/><span class=title>« Prev</span><br><span>Excluding generated code from JaCoCo report</span></a>
<a class=next href=https://wittchen.io/posts/writing-my-first-library-in-kotlin/><span class=title>Next »</span><br><span>Writing my first library in Kotlin</span></a></nav></footer></article></main><footer class=footer><span>&copy; 2024 <a href=https://wittchen.io/>Piotr Wittchen</a></span>
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg></a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(t){t.preventDefault();var e=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(e)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(e)}']`).scrollIntoView({behavior:"smooth"}),e==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${e}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script><script>document.querySelectorAll("pre > code").forEach(t=>{const n=t.parentNode.parentNode,e=document.createElement("button");e.classList.add("copy-code"),e.innerHTML="copy";function s(){e.innerHTML="copied!",setTimeout(()=>{e.innerHTML="copy"},2e3)}e.addEventListener("click",o=>{if("clipboard"in navigator){navigator.clipboard.writeText(t.textContent),s();return}const e=document.createRange();e.selectNodeContents(t);const n=window.getSelection();n.removeAllRanges(),n.addRange(e);try{document.execCommand("copy"),s()}catch(e){}n.removeRange(e)}),n.classList.contains("highlight")?n.appendChild(e):n.parentNode.firstChild==n||(t.parentNode.parentNode.parentNode.parentNode.parentNode.nodeName=="TABLE"?t.parentNode.parentNode.parentNode.parentNode.parentNode.appendChild(e):t.parentNode.appendChild(e))})</script></body></html>