<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="X-UA-Compatible" content="IE=edge"><title> Testing exceptions · Piotr Wittchen</title><meta name="description" content="Testing exceptions - Piotr Wittchen"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/"><link rel="stylesheet" href="/css/apollo.css"><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400"><link rel="search" type="application/opensearchdescription+xml" href="http://wittchen.io/atom.xml" title="Piotr Wittchen"><meta name="generator" content="Hexo 4.0.0"></head><body><div class="wrap"><header><a href="/" class="logo-link"><div>Piotr Wittchen</div></a><ul class="nav nav-list"><li class="nav-list-item"><a href="/archives" target="_self" class="nav-list-link">WRITING</a></li><li class="nav-list-item"><a href="/about" target="_self" class="nav-list-link">ABOUT</a></li><li class="nav-list-item"><a href="/code" target="_self" class="nav-list-link">CODE</a></li><li class="nav-list-item"><a href="/projects" target="_self" class="nav-list-link">PROJECTS</a></li><li class="nav-list-item"><a href="/talks" target="_self" class="nav-list-link">TALKS</a></li><li class="nav-list-item"><a href="/contact" target="_self" class="nav-list-link">CONTACT</a></li></ul></header><main class="container"><div class="post"><article class="post-block"><h1 class="post-title">Testing exceptions</h1><div class="post-info">Sep 4, 2018</div><div class="post-content"><p>In Java, we can test exceptions via unit tests in a few different ways. In this article, I’ll present common methods of doing that. Nevertheless, I suppose we there are different methods as well.</p>
<p>First method is basically wrapping a method call with try-catch block, assigning an exception to a variable and performing appropriate assertion. In these examples, I’m using <a href="https://junit.org" target="_blank" rel="noopener">JUnit</a> for unit tests and <a href="https://google.github.io/truth/" target="_blank" rel="noopener">Truth</a> for assertions.</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">@Test</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">shouldTestExceptionWithTryCatch</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  Exception caughtException = <span class="keyword">null</span>;</span><br><span class="line"></span><br><span class="line">  <span class="keyword">try</span> &#123;</span><br><span class="line">    <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeExcetpion(<span class="string">"message"</span>);</span><br><span class="line">  &#125; <span class="keyword">catch</span> (<span class="keyword">final</span> Exception e) &#123;</span><br><span class="line">    caughtException = e;</span><br><span class="line">  &#125;</span><br><span class="line"></span><br><span class="line">  assertThat(caughtException).hasMessageThat().isEqualTo(<span class="string">"message"</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>In the second method, we can define a type of the thrown exception within the <code>@Test</code> annotation. It’s useful approach when we don’t want to test exception details like message and we care only about the type.</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">@Test</span>(expected = RuntimeException.class)</span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">shouldTestExceptionWithExpectedAnnotation</span><span class="params">()</span> <span class="keyword">throws</span> RuntimeException </span>&#123;</span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeException(<span class="string">"message"</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>We can also test exceptions with AssertJ library as follows:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">@Test</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">shouldTestExceptionWithAssertJ</span><span class="params">()</span> <span class="keyword">throws</span> RuntimeException </span>&#123;</span><br><span class="line">  Throwable thrown = catchThrowable(<span class="keyword">this</span>::throwException);</span><br><span class="line"></span><br><span class="line">  org.assertj.core.api.Assertions</span><br><span class="line">      .assertThat(thrown)</span><br><span class="line">      .isInstanceOf(RuntimeException.class)</span><br><span class="line">      .hasMessage(EXCEPTION_MESSAGE);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>Another method allows us to test exception type, message and other details without wrapping method call with try-catch block, what increases code readibility and makes it clear. In order to achieve that, we need <code>@Rule</code> annotation and <code>ExpectedException</code> object like in the code snippet below. What is important in this example, we have to define assertions in the beginning and invoke method, which will throw an exception after these assertions. It’s different order than in a regular unit test.</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"></span><br><span class="line"><span class="meta">@Rule</span></span><br><span class="line"><span class="keyword">public</span> ExpectedException expectedException = ExpectedException.none();</span><br><span class="line"></span><br><span class="line"><span class="meta">@Test</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">shouldTestExceptionWithRuleAnnotation</span><span class="params">()</span> <span class="keyword">throws</span> RuntimeException </span>&#123;</span><br><span class="line">  expectedException.expect(RuntimeException.class);</span><br><span class="line">  expectedException.expectMessage(EXCEPTION_MESSAGE);</span><br><span class="line"></span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeException(<span class="string">"message"</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>Alternatively, we can experiment with <a href="https://www.vavr.io/" target="_blank" rel="noopener">Vavr</a> and <code>Try</code> interface.</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">@Test</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">shouldTestExceptionWithTryCatchAndVavr</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">final</span> Object object = </span><br><span class="line">    Try</span><br><span class="line">      .of(<span class="keyword">this</span>::throwException)</span><br><span class="line">      .toOption()</span><br><span class="line">      .getOrElse(<span class="keyword">new</span> ErrorObject());</span><br><span class="line"></span><br><span class="line">  assertThat(object).isInstanceOf(ErrorObject.class);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">private</span> Object <span class="title">throwException</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">throw</span> <span class="keyword">new</span> RuntimeException(<span class="string">"message"</span>);</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">private</span> <span class="class"><span class="keyword">class</span> <span class="title">ErrorObject</span> </span>&#123;&#125;</span><br></pre></td></tr></table></figure>

<p>We can even go crazy and prepare RxJava wrapper for our exception.</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">private</span> Completable <span class="title">toCompletable</span><span class="params">(<span class="keyword">final</span> Runnable runnable)</span> </span>&#123;</span><br><span class="line">  <span class="keyword">return</span> Completable.create(emitter -&gt; &#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">      runnable.run();</span><br><span class="line">      emitter.onComplete();</span><br><span class="line">    &#125; <span class="keyword">catch</span> (<span class="keyword">final</span> Exception e) &#123;</span><br><span class="line">      emitter.onError(e);</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>and write test like that:</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">@Test</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">shouldTestExceptionWithRxJava</span><span class="params">()</span> </span>&#123;</span><br><span class="line">  <span class="keyword">final</span> Throwable throwable = toCompletable(<span class="keyword">this</span>::throwException).blockingGet();</span><br><span class="line"></span><br><span class="line">  assertThat(throwable).isInstanceOf(RuntimeException.class);</span><br><span class="line">  assertThat(throwable.getMessage()).isEqualTo(EXCEPTION_MESSAGE);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>For sure, it shouldn’t be default choice and I wrote it just for a little experiment. Don’t treat that as a production-ready code (unless there’s a reson you really need something like that).</p>
<p>I think, we can find even more ways of testing exceptions. In my opinion, solution with JUnit and <code>@Rule</code> annotation is the cleanest and most flexible one among all of the approaches presented here. It’s good to mention that last two approaches are just experiments. I also recommend Truth for writing assertions. Nevertheless, libraries like FEST, AssertJ and others, which have fluent interfaces helping in error analysis are also worth considering in daily usage.</p>
<p>Do you know other (maybe better) approaches of testing exceptions in Java? Share them in comments :-).</p>
</div></article></div></main><footer><div class="paginator"><a href="/excluding-generated-code-from-jacoco-report/" class="prev">PREV</a><a href="/writing-my-first-library-in-kotlin/" class="next">NEXT</a></div><div id="disqus_thread"></div><script>var disqus_shortname = 'wittchenio';
var disqus_identifier = 'testing-exceptions/';
var disqus_title = 'Testing exceptions';
var disqus_url = 'http://wittchen.io/testing-exceptions/';
(function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();</script><script id="dsq-count-scr" src="//undefined.disqus.com/count.js" async></script><div class="copyright"><p>© 2013 - 2019 <a href="http://wittchen.io">Piotr Wittchen</a></p><p><a href="https://github.com/pwittchen/wittchen.io" target="_blank" rel="noopener">source</a> / <a href="/feed.xml">rss</a> / <a href="/archives">archives</a> / <a href="/tags">tags</a> / <a href="https://github.com/pwittchen/wittchen.io#rest" target="_blank" rel="noopener">api</a> / <a href="/gh">github</a> / <a href="/so">stackoverflow</a> / <a href="/in">linkedin</a> / <a href="mailto:piotr@wittchen.io">email</a></p></div></footer></div><script async src="//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML" integrity="sha384-crwIf/BuaWM9rM65iM+dWFldgQ1Un8jWZMuh3puxb8TOY9+linwLoI7ZHZT+aekW" crossorigin="anonymous"></script><script>(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;e=o.createElement(i);r=o.getElementsByTagName(i)[0];e.src='//www.google-analytics.com/analytics.js';r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));ga('create',"UA-2194664-7",'auto');ga('send','pageview');</script></body></html>